// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujubhmpadbhkxuhaxxxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdWJobXBhZGJoa3h1aGF4eHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTcyMTcsImV4cCI6MjA1NDU5MzIxN30.Yiy8tYyEMTN8VDmvElLx_Jmg2HFws6TsOMXDfgItdDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);